### ISSUE TITLE
Can't overwrite hw_1_svc

### ISSUE THREAD

**Issue by jonasribeiro** [JulesWang/helloworld-RPC#1]
Is there any way to do it?

I would like to send 1000 messages of the same size between client <-> server, and afterwards change the message size starting at 1byte, 2bytes, 4bytes till 32768bytes

For this I need to add an argument in hw_1_svc (the message), and treat the loops in the client side

I will get which time the client send the message and receive the answer as well, so I can do some research in the delay according to the message size and bandwith between client and server

Thanks

**Comment by JulesWang** [comment]
I think quora or stackoverflow is a better place for your question. :-)
